apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/my-pc/"

--- 
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: my-pv 
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: Pod 
metadata:
  name: pvc-pod
spec:
  nodeName: master
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh"]
    args: [ "-c", "while true; do echo $(date) >> /data/date.txt; sleep 10; done"]
    volumeMounts:
    - mountPath: /data
      name: my-pv
  volumes:  
    - name: my-pv
      persistentVolumeClaim:
        claimName: my-pvc 