---
global:

route:
  group_wait: 10s
  group_interval: 15s
  receiver: 'default'
  routes:
    - match:
        team: "team_b"
      receiver: 'NODE_DOWN'
    - match:
        cpu: "HIGH_CPU"
      receiver: "HIGH_CPU"

receivers:
  - name: 'default'
    email_configs:
      - to: khaledhawil91@gmail.com
        from: khaledhawil91@gmail.com
        smarthost: "smtp.gmail.com:587"
        auth_username: khaledhawil91@gmail.com
        auth_password: "hstr nkhi guca oqgn"
        auth_identity: khaledhawil91@gmail.com

  - name: 'HIGH_CPU'
    email_configs:
      - to: khaledhawil91@gmail.com
        from: khaledhawil91@gmail.com
        smarthost: "smtp.gmail.com:587"
        auth_username: khaledhawil91@gmail.com
        auth_password: "hstr nkhi guca oqgn"
        auth_identity: khaledhawil91@gmail.com
        send_resolved: true
  - name: 'NODE_DOWN'
    slack_configs:
      - channel: "#default"
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'