version: "3.8"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - "/home/spider/Downloads/metube:/downloads"
    environment:
      OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
      UID: 1000
      GID: 1000