apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dolfined-rb
  namespace: default
subjects:
- kind: User
  name: dolfined
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: dolfined-role
  apiGroup: rbac.authorization.k8s.io