apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["echo", "Hello Whole!"]
      restartPolicy: Never
---

apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["sleep", "80"]
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  completions: 2
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["sleep", "80"]
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["sleep", "15"]
      restartPolicy: Never