apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["echo", "Hello Whole!"]
      restartPolicy: Never
---

apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["sleep", "80"]
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  completions: 2
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["sleep", "80"]
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: joker
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      containers:
      - name: joker
        image: alpine
        command: ["sleep", "15"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing-job
spec:
  completions: 1
  parallelism: 3
  template:
    spec:
      containers:
      - name: processor
        image: busybox
        command: ["sh", "-c", "echo 'Processing chunk $(MY_CHUNK)...' && sleep 20 && echo 'Chunk $(MY_CHUNK) processed.'"]
        env:
        - name: MY_CHUNK
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never    